const STUDIO_COPY = {
    action: "操作",
    about: "关于",
    actionRejected: "操作被拒绝",
    actionStage: "操作阶段",
    actionsUnavailable: "操作不可用",
    addWorkflow: "添加 Workflow",
    adoption: "采纳",
    adoptionActionsUnavailable: "采纳操作不可用",
    adoptionHistory: "采纳历史",
    advanced: "高级",
    advancedSettingsSaved: "高级设置已保存。",
    agent: "Agent",
    agentId: "ID",
    agentIntegrations: "Agent 集成",
    agentName: "名称",
    agentSkill: "Agent Skill",
    agents: "Agents",
    alreadyReviewed: "已处理",
    attach: "附加",
    attachStage: "附加阶段",
    artifacts: "产物",
    artifactTotal: "个产物",
    artifactInfo: "产物信息",
    attemptCount: "尝试次数",
    attemptUnit: "次尝试",
    autoRefresh: "自动刷新",
    adapter: "工具",
    adapterTimeout: "Agent 超时秒数",
    authoritative: "权威",
    call: "调用",
    callAdoptionActions: "调用采纳操作",
    calls: "调用",
    callsSubtitle: "审查单次 agent 调用、输出和本地采纳证据。",
    callWarnings: "调用警告",
    capabilities: "能力",
    cancel: "取消",
    commandLineTool: "命令行工具",
    commandLineInstall: "安装命令行工具",
    commandLineUpdate: "更新命令行工具",
    commandLineReinstall: "重新安装命令行工具",
    installedVersion: "已安装版本",
    latestVersion: "npm 最新版本",
    commandLinePath: "PATH 命令",
    configuredPath: "配置路径",
    closeReviewerSession: "关闭会话",
    compatibilityDiagnostics: "诊断说明",
    compatibilityFile: "兼容性文件",
    danglingOutput: "输出路径悬空",
    completed: "已完成",
    config: "配置",
    configSubtitle: "管理 Agents、Workflows、MCP 和 Agent 生命周期。",
    configView: "配置视图",
    confirmDelete: "确认删除",
    createAgent: "创建 Agent",
    createPreset: "创建 Preset",
    createWorkflow: "创建 Workflow",
    definitions: "手册",
    definitionsSubtitle: "查阅 AgentMesh 架构、概念、Packet 和使用路径。",
    delete: "删除",
    deleteWarning: "删除后不可撤销，请确认后继续。",
    details: "详情",
    diagnosticCount: "条诊断",
    diagnostics: "诊断",
    detected: "已找到",
    directCall: "直接调用",
    disable: "停用",
    disabledStatus: "已停用",
    displayName: "显示名称",
    dispatch: "分发",
    edit: "编辑",
    editAgent: "编辑 Agent",
    editPreset: "编辑 Preset",
    editWorkflow: "编辑 Workflow",
    enable: "启用",
    enabledStatus: "已启用",
    environment: "环境",
    expiresAt: "过期时间",
    events: "事件",
    eventCount: "事件数",
    exit: "退出码",
    exitCodeNotRecorded: "未记录",
    executionPolicy: "执行策略",
    failureSummary: "失败摘要",
    findings: "问题",
    flowActions: "流程操作",
    forceRefreshFiles: "刷新已有文件",
    fallbackAgents: "Fallback Agent",
    fallbackAttempts: "Fallback 尝试次数",
    fallbackSettings: "Fallback 设置",
    fallbackTimeout: "Fallback 超时秒数",
    generatedAt: "生成时间",
    hermetic: "独立上下文",
    host: "宿主",
    importSource: "导入来源",
    importToml: "选择 TOML",
    installed: "已安装",
    installedTargets: "已安装目标",
    installSelectedSkills: "安装选中的 Skill",
    completedAt: "结束",
    createdAt: "创建时间",
    currentStatus: "当前",
    currentNode: "当前节点",
    currentEntrypoint: "当前入口",
    defaultAgents: "默认 Agent",
    duration: "耗时",
    idle: "空闲",
    latestEventFallback: "暂无事件",
    latestEvent: "最新事件",
    loginShellProbe: "登录 Shell",
    loadingConfig: "正在加载配置...",
    loadingModels: "正在拉取模型...",
    loadingResources: "正在加载资源...",
    loadingAgents: "正在加载 Agents...",
    loadingIntegrations: "正在加载集成状态...",
    loadingWorkspaceStatus: "正在加载工作区状态...",
    localEvidenceMarker: "本地证据标记",
    localEvidenceNote: "这里只标记本地审查状态，不代表输出已经提交或发布。",
    locked: "已锁定",
    lastUpdatedAt: "最后更新时间",
    lastUsedAt: "上次使用",
    lastWriter: "最后写入方",
    markedLocalEvidence: "已标记为本地证据",
    mcp: "MCP",
    metadataState: "元数据状态",
    manualInput: "手动填写",
    minReadRuntimeVersion: "最低读取版本",
    minWriteRuntimeVersion: "最低写入版本",
    model: "模型",
    name: "名称",
    needsAttention: "需要处理",
    noAdoptionEvents: "暂无采纳事件",
    noAgents: "暂无 Agents。",
    noArtifacts: "暂无产物。",
    noConfig: "无法加载配置",
    noModelsFound: "未发现可选模型",
    noResources: "无法加载资源",
    noIntegrations: "无法加载集成状态",
    noMcpServers: "暂无 MCP server。",
    noMutationOutput: "暂无操作输出。",
    noExternalProcess: "无外部进程",
    noArtifactsForCurrentNode: "当前节点暂无产物",
    noCurrentNode: "暂无当前节点",
    noPreviewContent: "暂无可预览内容。",
    notConfigured: "未设置",
    noPromptRecorded: "暂无 prompt 记录。",
    noPresets: "暂无 Presets。",
    noOutputFile: "暂无 output 文件。",
    noRawReviews: "暂无原始审查。",
    noReviewerSessions: "当前运行没有可管理的 Reviewer Session。",
    noRelatedItems: "暂无记录",
    noStderrRecorded: "暂无 stderr 记录。",
    noTiming: "暂无时间",
    noVerdict: "暂无结论",
    noWorkflow: "暂无 Workflows。",
    noWorkflows: "暂无 Workflows。",
    oneItemPerLine: "每行一个",
    emptyUsesDefaultArtifacts: "留空时按阶段自动补齐",
    artifactCount: "产物数",
    contextPolicy: "上下文策略",
    packetSchemaVersion: "Packet Schema 版本",
    path: "路径",
    pendingStatus: "待开始",
    preview: "预览",
    previewLoadFailed: "预览加载失败",
    presetDescription: "说明",
    presetId: "内部 ID",
    presetName: "名称",
    presetToml: "Preset TOML",
    presetTomlRequired: "请选择 Preset TOML 文件。",
    presetWorkflowId: "关联 Workflow",
    presets: "Presets",
    prompt: "Prompt",
    purgeExpiredReviewerSessions: "清理已过期会话",
    project: "项目",
    purpose: "目的",
    rawReviews: "原始审查",
    readOnly: "只读",
    readWrite: "可读写",
    refused: "拒绝",
    refreshExistingFiles: "刷新已有文件",
    related: "关联",
    relatedCall: "关联调用",
    relatedCommit: "关联提交",
    relatedFiles: "关联文件",
    relatedRun: "关联运行",
    releaseSummary: "发布摘要",
    releaseVerdict: "发布结论",
    rejected: "已拒绝",
    accepted: "已接受",
    accept: "接受",
    reject: "拒绝",
    needsDecision: "需要决策",
    residualRisk: "剩余风险",
    retry: "重试",
    retryAttempts: "重试次数",
    runtimeVersion: "运行时版本",
    resume: "恢复",
    reEnable: "重新启用",
    reasoningEffort: "推理等级",
    resources: "资源",
    resourceView: "资源视图",
    reviewRelease: "审查 / 发布",
    reviewerSessions: "Reviewer Session",
    run: "运行",
    runDiagnostics: "运行诊断",
    runDirectory: "运行目录",
    running: "运行中",
    stage: "阶段",
    stageAssignments: "阶段分配",
    stageDefaultAgents: "阶段默认 Agent",
    stages: "阶段",
    startedAt: "开始",
    status: "状态",
    statusCompleted: "已完成",
    statusFailed: "失败",
    callDetailsFailed: "调用详情加载失败",
    loadingCallDetails: "正在加载调用详情...",
    loadingCalls: "正在加载调用...",
    loadingRunDetails: "正在加载运行详情...",
    loadingRuns: "正在加载运行...",
    noMatchingCalls: "没有匹配的调用。",
    noMatchingRuns: "没有匹配的运行。",
    noCalls: "暂无调用。",
    noRuns: "暂无运行。",
    overview: "总览",
    refreshCalls: "刷新调用",
    refreshRuns: "刷新运行",
    release: "发布 / 审查",
    callListFailed: "调用加载失败",
    runListFailed: "运行加载失败",
    runDetailsFailed: "运行详情加载失败",
    runs: "运行",
    runsSubtitle: "查看详情、操作、日志和诊断。",
    searchCalls: "搜索调用",
    searchCallsPlaceholder: "搜索调用",
    searchRuns: "搜索运行",
    searchRunsPlaceholder: "搜索运行",
    sessionMode: "会话模式",
    saveChanges: "保存修改",
    saveAdvancedSettings: "保存高级设置",
    selectedCount: "已选",
    selectModel: "选择模型",
    selectStages: "选择阶段",
    selectTomlFile: "选择要导入的 TOML 文件",
    selectArtifact: "请选择产物。",
    selectCall: "请选择调用。",
    selectAgents: "选择一个或多个 Agent",
    selectWorkflow: "选择 Workflow",
    selectWorkflowFirst: "先选择 Workflow 后配置阶段 Agent。",
    selectRun: "请选择运行。",
    settings: "设置",
    settingsSubtitle: "管理资源、环境集成和版本信息。",
    settingsView: "设置视图",
    skippedChecks: "跳过的检查",
    stdout: "stdout",
    stderr: "stderr",
    output: "输出",
    optional: "可选",
    reason: "原因",
    reasonPlaceholder: "说明为什么要标记这次调用",
    supersede: "取代",
    requiredForSuperseded: "取代时必填",
    supersededByCall: "被调用取代",
    targetMissing: "未找到",
    textArtifact: "文本产物",
    cliDiagnostics: "CLI 检测",
    tool: "工具",
    tomlFile: "TOML 文件",
    tomlReadFailed: "TOML 文件读取失败。",
    truncated: "已截断",
    type: "类型",
    updatedAt: "更新时间",
    upgradeBeforeMutating: "请先升级 AgentMesh，再修改这个工作区。",
    upgradeBeforeReading: "请先升级 AgentMesh，再读取或修改这个工作区。",
    unknown: "未知",
    unsupportedSchema: "不支持的 schema",
    user: "用户",
    userConfig: "用户配置",
    userDefaults: "用户默认值",
    pathSource: "PATH",
    source: "来源",
    appPreference: "App 偏好",
    wellKnownPath: "常见路径",
    allowAutoDispatch: "允许自动分发",
    requireUserGate: "需要用户确认",
    version: "版本",
    versionInfo: "版本信息",
    viewNavigation: "页面视图",
    workflow: "Workflow",
    yes: "是",
    no: "否",
    workflowDescription: "说明",
    workflowFlow: "Workflow Flow",
    workflowId: "内部 ID",
    workflowName: "名称",
    workflowNodes: "Workflow Nodes",
    workflowPacketArtifacts: "产物文件",
    workflowPacketArtifactsHelp: "最后要交付什么",
    workflowQualityGates: "质量门禁",
    workflowQualityGatesHelp: "怎样才算合格",
    workflowSources: "Workflow Sources",
    workflowStages: "阶段",
    workflowToml: "Workflow TOML",
    workflowTomlRequired: "请选择 Workflow TOML 文件。",
    workflowWhenToUse: "使用场景",
    workflowWhenToUseHelp: "什么时候该用它",
    workflows: "Workflows",
    workspace: "工作区",
    workspaceStatusUnavailable: "无法读取工作区状态",
    logEvents: "日志",
    policyConfigured: "已记录",
    policyNotRecorded: "未记录",
} as const;

export type StudioCopyKey = keyof typeof STUDIO_COPY;

interface StudioCopyValue {
  t: (key: StudioCopyKey) => string;
}

const studioCopy: StudioCopyValue = {
  t: (key) => STUDIO_COPY[key],
};

export function useStudioCopy(): StudioCopyValue {
  return studioCopy;
}
